# Authoritative TP2 entity table: (internal_name, display_name, theme)
# Source: complete in-game list derived from existing files. This is the canonical set of valid
# spawnable entity names plus their display labels and themes. Used by tp2assets for the
# asset-browser catalog, display names, and theme categorization.

ENTITIES = [
    # --- Modern (lab) ---
    ("candy_red", "Red Candy", "Modern"),
    ("candy_green", "Green Candy", "Modern"),
    ("candy_yellow", "Yellow Candy", "Modern"),
    ("candy_pink", "Pink Candy", "Modern"),
    ("candy_purple", "Purple Candy", "Modern"),
    ("candy_brown", "Brown Candy", "Modern"),
    ("candy_orange", "Orange Candy", "Modern"),
    ("candy_blue", "Blue Candy", "Modern"),
    ("testtube1", "Test Tube", "Modern"),
    ("battery", "Battery", "Modern"),
    ("calliper", "Calliper", "Modern"),
    ("eyedropper", "Eyedropper", "Modern"),
    ("petridish", "Petri Dish", "Modern"),
    ("hotplate", "Hot Plate", "Modern"),
    ("flask", "Flask", "Modern"),
    ("oscilloscope", "Oscilloscope", "Modern"),
    ("chalk", "Chalk", "Modern"),
    ("bunsun", "Bunsen Burner", "Modern"),
    ("paper", "Paper", "Modern"),
    ("microscope", "Microscope", "Modern"),
    ("scientist_young_lab_1", "Young Scientist", "Modern"),
    ("scientist_old_lab_1", "Old Scientist", "Modern"),
    ("timemachine", "Time Machine", "Modern"),
    ("simon_lab1", "Simon", "Modern"),
    ("rat_lab1", "Lab Rat", "Modern"),
    ("frog_lab1", "Frog", "Modern"),
    ("rat_lab2", "Lab Rat", "Modern"),
    ("simon_labfarattack", "Simon", "Modern"),
    ("scientist_old_lab3", "Old Scientist", "Modern"),
    ("scientist_young_lab3", "Young Scientist", "Modern"),

    # --- General ---
    ("boulder1", "Boulder", "General"),
    ("boulder2", "Boulder", "General"),
    ("rock1", "Rock", "General"),
    ("rock2", "Rock", "General"),
    ("tree_birch", "Birch Tree", "General"),
    ("tree_oak", "Oak Tree", "General"),
    ("tree_maple", "Maple Tree", "General"),
    ("tree_redwood", "Redwood Tree", "General"),
    ("leaf", "Cucumber Leaf", "General"),
    ("pebble1", "Pebble", "General"),
    ("pebble2", "Pebble", "General"),
    ("larva_dino1", "Larva", "General"),
    ("goo_enemy_future1", "Goo Enemy", "General"),

    # --- Dino ---
    ("magnolia", "Magnolia", "Dino"),
    ("fern1", "Fern", "Dino"),
    ("bone1", "Small Bone", "Dino"),
    ("bone2", "Large Bone", "Dino"),
    ("bone3", "Pelvic Bone", "Dino"),
    ("bone4", "Spine Bone", "Dino"),
    ("bone5", "Skull Bone", "Dino"),
    ("aphid_dino1", "Aphid", "Dino"),
    ("twig", "Twig", "Dino"),
    ("termite_dino1", "Termite", "Dino"),
    ("snail_dino1", "Snail", "Dino"),
    ("mushroom1", "White Mushroom", "Dino"),
    ("ant_dino2", "Ant", "Dino"),
    ("leaf_maple", "Maple Leaf", "Dino"),
    ("butterfly1_dino1", "Butterfly", "Dino"),
    ("butterfly2_dino1", "Butterfly", "Dino"),
    ("grasshopper_dino1", "Grasshopper", "Dino"),
    ("grasshopper_dino2", "Grasshopper", "Dino"),
    ("feather1", "Feather", "Dino"),
    ("feather2", "Feather", "Dino"),
    ("egg1", "Egg", "Dino"),
    ("mushroom3", "Mushroom", "Dino"),
    ("cimolestes_dino1", "Cimolestes", "Dino"),
    ("cimolestes_dino2", "Cimolestes", "Dino"),
    ("dragonfly_dino1", "Dragonfly", "Dino"),
    ("agomphus_dino1", "Agomphus", "Dino"),
    ("agomphus_dino2", "Agomphus", "Dino"),
    ("oryctodromeus_dino1", "Oryctodromeus", "Dino"),
    ("stygimoloch_dino1", "Stygimoloch", "Dino"),
    ("stygimoloch_dino2", "Stygimoloch", "Dino"),
    ("bambiraptor_dino1", "Bambiraptor", "Dino"),
    ("bambiraptor_dino2", "Bambiraptor", "Dino"),
    ("stegoceras_dino1", "Stegoceras", "Dino"),
    ("stegoceras_dino2", "Stegoceras", "Dino"),
    ("troodon_dino1", "Troodon", "Dino"),
    ("sheddedskin1", "Shedded Skin", "Dino"),
    ("alamosaurus_dino1", "Alamosaurus", "Dino"),
    ("nothronychus_dino1", "Nothronychus", "Dino"),
    ("nothronychus_dino2", "Nothronychus", "Dino"),
    ("albertosaurus_dino1", "Albertosaurus", "Dino"),
    ("euoplocephalus_dino1", "Euoplochephalus", "Dino"),
    ("nanotyrannus_dino1", "Nanotyrannus", "Dino"),
    ("pachyrhinosaurus_dino1", "Pachyrhinosaurus", "Dino"),
    ("styracosaurus_dino1", "Styracosaurus", "Dino"),
    ("styracosaurus_dino2", "Styracosaurus", "Dino"),
    ("triceratops_dino1", "Triceratops", "Dino"),
    ("maiasaura_dino1", "Maiasaura", "Dino"),
    ("maiasaura_dino2", "Maiasaura", "Dino"),
    ("corythosaurus_dino1", "Corythosaurus", "Dino"),
    ("parasaurolophus_dino1", "Parasaurolophus", "Dino"),
    ("tyrannosaurus_dino1", "Tyrannosaurus", "Dino"),
    ("tyrannosaurus_dino2", "Tyrannosaurus", "Dino"),
    ("lava", "Lava", "Dino"),
    ("mountain1", "Mountain", "Dino"),
    ("mountain2", "Mountain", "Dino"),
    ("mountain3", "Mountain", "Dino"),
    ("volcano", "Volcano", "Dino"),
    ("struthiomimus_dino1", "Struthiomimus", "Dino"),
    ("struthiomimus_dino2", "Struthiomimus", "Dino"),
    ("struthiomimus_dino3", "Struthiomimus", "Dino"),
    ("lily1", "Lily", "Dino"),
    ("alphadon_dino1", "Alphadon", "Dino"),
    ("stick", "Stick", "Dino"),
    ("deinosuchus_dino1", "Deinosuchus", "Dino"),
    ("deinosuchus_dino2", "Deinosuchus", "Dino"),
    ("worm_dino1", "Worm", "Dino"),
    ("ant_explosive1", "Ant", "Dino"),

    # --- Egypt ---
    ("larva_egypt1", "Larva", "Egypt"),
    ("earings", "Earing", "Egypt"),
    ("ring", "Ring", "Egypt"),
    ("scarab_egypt1", "Scarab", "Egypt"),
    ("canopicjar1", "Canopic Jar", "Egypt"),
    ("canopicjar2", "Canopic Jar", "Egypt"),
    ("bracelet", "Bracelet", "Egypt"),
    ("locust_egypt1", "Locust", "Egypt"),
    ("natron", "Natron", "Egypt"),
    ("necklace", "Necklace", "Egypt"),
    ("oillamp", "Oil Lamp", "Egypt"),
    ("seti", "Seti Board Game", "Egypt"),
    ("uraeus", "Uraeus", "Egypt"),
    ("crook", "Crook", "Egypt"),
    ("deathmask", "Burial Mask", "Egypt"),
    ("flail", "Flail", "Egypt"),
    ("linen", "Linen", "Egypt"),
    ("papyrus", "Papyrus", "Egypt"),
    ("spear", "Spear", "Egypt"),
    ("collar", "Collar", "Egypt"),
    ("staff", "Staff", "Egypt"),
    ("mau_egypt1", "Egyptian Mau", "Egypt"),
    ("mau_egypt2", "Egyptian Mau", "Egypt"),
    ("mau_egypt3", "Egyptian Mau", "Egypt"),
    ("mau_kitten_egypt1", "Mau Kitten", "Egypt"),
    ("egypt_peasant_egypt1", "Worker", "Egypt"),
    ("egypt_peasant_egypt2", "Worker", "Egypt"),
    ("statue1", "Statue", "Egypt"),
    ("statue2", "Statue", "Egypt"),
    ("egypt_soldier_egypt1", "Soldier", "Egypt"),
    ("egypt_soldier_egypt2", "Soldier", "Egypt"),
    ("egypt_noble_egypt1", "Noble Woman", "Egypt"),
    ("egypt_noble_egypt2", "Noble Woman", "Egypt"),
    ("mummy", "Mummy", "Egypt"),
    ("table", "Table", "Egypt"),
    ("egypt_poor_house_1", "House", "Egypt"),
    ("egypt_poor_house_2", "House", "Egypt"),
    ("egypt_poor_house_3", "House", "Egypt"),
    ("egypt_rich_house_1", "House", "Egypt"),
    ("egypt_rich_house_2", "House", "Egypt"),
    ("egypt_rich_house_3", "House", "Egypt"),
    ("egypt_rich_house_4", "House", "Egypt"),
    ("egypt_rich_house_5", "House", "Egypt"),
    ("egypt_rich_house_6", "House", "Egypt"),
    ("egypt_poor_house_eight", "Houses", "Egypt"),
    ("egypt_rich_house_four", "Houses", "Egypt"),
    ("watusi_egypt1", "Watusi", "Egypt"),
    ("watusi_egypt2", "Watusi", "Egypt"),
    ("stoneblock1", "Stone Block", "Egypt"),
    ("stoneblock1_pushable", "Stone Block", "Egypt"),
    ("palmtree", "Palm Tree", "Egypt"),
    ("hippo_egypt1", "Hippopotamus", "Egypt"),
    ("hippo_egypt2", "Hippopotamus", "Egypt"),
    ("hippo_baby1", "Baby Hippo", "Egypt"),
    ("Arabian Horse", "Arabian Horse", "Egypt"),
    ("horse_baby_egypt1", "Arabian Foal", "Egypt"),
    ("horse_egypt2", "Horse", "Egypt"),
    ("croc_egypt1", "Crocodile", "Egypt"),
    ("croc_egypt3", "Crocodile", "Egypt"),
    ("sphinx", "Sphinx", "Egypt"),
    ("pyramid", "Pyramid", "Egypt"),
    ("sarcophagus", "Sarcophagus", "Egypt"),
    ("coffin", "Coffin", "Egypt"),
    ("rat_egypt1", "Rat", "Egypt"),
    ("jackal_egypt1", "Jackal", "Egypt"),
    ("cobra_egypt1", "Cobra", "Egypt"),

    # --- Future ---
    ("bacteria1_future1", "Bacterium", "Future"),
    ("bacteria2_future1", "Bacterium", "Future"),
    ("bacteria3_future1", "Bacterium", "Future"),
    ("nanobot_future1", "Nanobot", "Future"),
    ("pollen1_future1", "Pollen", "Future"),
    ("pollen2_future1", "Pollen", "Future"),
    ("amoeba1_future1", "Amoeba", "Future"),
    ("ant_future1", "Laser Ant", "Future"),
    ("creditchip", "Credit Chip", "Future"),
    ("fusioncell", "Fusion Cell", "Future"),
    ("solarpanel", "Solar Panel", "Future"),
    ("raindrop", "Water", "Future"),
    ("writingpad", "Pad Computer", "Future"),
    ("rat_future1", "Laser Rat", "Future"),
    ("rat_future2", "Laser Rat", "Future"),
    ("raygun", "Raygun", "Future"),
    ("brain_watch1", "Brain", "Future"),
    ("hoverboard", "Hoverboard", "Future"),
    ("vacuum_future1", "Sentient Vacuum Cleaner", "Future"),
    ("vacuum_future2", "Sentient Vacuum Cleaner", "Future"),
    ("future_person_blue_1", "Humanoid", "Future"),
    ("future_person_green_1", "Humanoid", "Future"),
    ("future_person_greyalien_1", "Humanoid", "Future"),
    ("future_person_white_1", "Humanoid", "Future"),
    ("hovercar_float1", "Hovercar", "Future"),
    ("hovercar_future1", "Hovercar", "Future"),
    ("hovercar_stationary1", "Hovercar", "Future"),
    ("hoverguy_future1", "Hoverboarder", "Future"),
    ("futurebuilding1", "Building", "Future"),
    ("futurebuilding2", "House", "Future"),
    ("future_tank_1", "Laser Tank", "Future"),
    ("future_tank_2", "Laser Tank", "Future"),
    ("laserbolt_tank2", "Laser Tank", "Future"),
    ("shuttlecraft_stationary", "Shuttlecraft", "Future"),
    ("shuttlecraft_fight1", "Shuttlecraft", "Future"),
    ("asteroid1_future1", "Asteroid", "Future"),
    ("asteroid2_future1", "Asteroid", "Future"),
    ("asteroid1_future2", "Asteroid", "Future"),
    ("asteroid2_future2", "Asteroid", "Future"),
    ("asteroid1_future3", "Asteroid", "Future"),
    ("asteroid2_future3", "Asteroid", "Future"),
    ("spacestation_future1", "Space Station", "Future"),
    ("ufo_future1", "Flying Saucer", "Future"),
    ("earth_future1", "Earth", "Future"),
    ("earth_future2", "Earth", "Future"),
    ("moon_future1", "Moon", "Future"),
    ("mars_future1", "Mars", "Future"),
    ("mercury_future1", "Mercury", "Future"),
    ("venus_future1", "Venus", "Future"),
    ("jupiter_future1", "Jupiter", "Future"),
    ("neptune_future1", "Neptune", "Future"),
    ("saturn_future1", "Saturn", "Future"),
    ("uranus_future1", "Uranus", "Future"),
    ("sun", "Sun", "Future"),
    ("star", "Star", "Future"),
    ("redgiant", "Red Giant", "Future"),
    ("supergiant", "Super Giant", "Future"),
    ("hypergiant", "Hyper Giant", "Future"),
    ("hypergiant_moving", "Hyper Giant", "Future"),
    ("blackhole", "Black Hole", "Future"),
    ("nebula1_future1", "Nebula", "Future"),
    ("nebula2_future1", "Nebula", "Future"),
    ("starcluster_future1", "Star Cluster", "Future"),
    ("galacticdust", "Galactic Dust", "Future"),
    ("galacticcore", "Galactic Core", "Future"),
    ("galaxyelliptical_future1", "Elliptical Galaxy", "Future"),
    ("galaxyspiral_future1", "Spiral Galaxy", "Future"),
    ("galaxygroup_future1", "Galaxy Group", "Future"),
    ("galaxycluster_future1", "Galaxy Cluster", "Future"),
    ("supercluster_future1", "Supercluster", "Future"),
    ("fabricspace", "Fabric of the Universe", "Future"),
    ("galacticturtle", "Turtle of Time", "Future"),
    ("simon_future1", "Laser Cat", "Future"),
    ("simon_future2", "Laser Cat", "Future"),
    ("simon_future3", "Laser Cat", "Future"),

    # --- Japan ---
    ("rice", "Grain of Rice", "Japan"),
    ("cherry_blossom_petal", "Petal", "Japan"),
    ("cherry_blossom", "Cherry Blossom", "Japan"),
    ("shuriken", "Shuriken", "Japan"),
    ("buddha_statue_1", "Statue", "Japan"),
    ("buddha_statue_2", "Statue", "Japan"),
    ("japanfish", "Fish", "Japan"),
    ("tanto", "Tanto", "Japan"),
    ("teapot", "Teapot", "Japan"),
    ("katana", "Katana", "Japan"),
    ("wakizashi", "Wakizashi", "Japan"),
    ("samurai_japan1", "Samurai", "Japan"),
    ("samurai_japan2", "Samurai", "Japan"),
    ("ninja_japan1", "Ninja", "Japan"),
    ("ninja_japan2", "Ninja", "Japan"),
    ("cherry_tree", "Cherry Blossom Tree", "Japan"),
    ("japan_small_house", "House", "Japan"),
    ("japan_big_house", "House", "Japan"),
    ("japanmonster_japan1", "Monsterzilla", "Japan"),
    ("japanmonster_japan2", "Monsterzilla", "Japan"),
    ("mouse_japan1", "Mouse", "Japan"),

    # --- Rome ---
    ("raisin", "Raisin", "Rome"),
    ("purple_grape", "Purple Grape", "Rome"),
    ("green_grape", "Green Grape", "Rome"),
    ("green_olive", "Green Olive", "Rome"),
    ("purple_olive", "Purple Olive", "Rome"),
    ("oyster", "Oyster", "Rome"),
    ("goblet", "Goblet", "Rome"),
    ("amphorae", "Amphorae", "Rome"),
    ("bread", "Bread", "Rome"),
    ("romanfish", "Fish", "Rome"),
    ("roman_man_rome1", "Roman Man", "Rome"),
    ("roman_woman_rome1", "Roman Woman", "Rome"),
    ("roman_soldier_rome1", "Roman Soldier", "Rome"),
    ("romanstatue1", "Roman Statue", "Rome"),
    ("romanstatue2", "Roman Statue", "Rome"),
    ("house_1", "Roman House", "Rome"),
    ("house_2", "Roman House", "Rome"),
    ("ballista_rome1", "Ballista", "Rome"),
    ("ballista_rome3", "Ballista", "Rome"),
    ("temple", "Roman Building", "Rome"),
    ("colosseum", "Coliseum", "Rome"),
    ("romanhouses", "Roman Houses", "Rome"),
    ("roman_glad_rome1", "Roman Gladiator", "Rome"),
    ("roman_glad_rome2", "Roman Gladiator", "Rome"),
    ("lion_rome1", "Lion", "Rome"),
    ("lion_rome2", "Lion", "Rome"),
    ("mosaic_1", "Tile", "Rome"),
    ("mosaic_2", "Tile", "Rome"),
    ("rat_rome1", "Rat", "Rome"),
]

# convenience maps
DISPLAY = {n: d for (n, d, t) in ENTITIES}
THEME = {n: t for (n, d, t) in ENTITIES}
